### ISSUE TITLE
Amount : Must be an integer

### ISSUE THREAD

**Issue by youalibala** [payfort/start.net#6]
Why payfort only accept integer? What in case I Choose currency->USD and want to receive an amount in decimal (20.50$)

**{
  "amount": [
    "must be an integer"
  ],
  "card": []
}**

**Comment by alovak** [comment]
@youalibala thanks for your question.

[Here](https://docs.start.payfort.com/references/api/#create-a-new-charge) you can find that amount should be in smallest units (cents for USD). For your amount 20.50$ you have to pass value as 2050.

**Comment by youalibala** [comment]
Well, Thanks @alovak
